services:
  flask-app:
    build:
      context: ./flask-app
    user: root
    ports:
      - "8888:5000"
    volumes:
      - zap-reports:/usr/src/reports
    networks:
      - internal-network
    depends_on:
      - zap-scanner
  zap-scanner:
    build:
      context: ./zap-scanner
    user: root
    expose:
      - "3030"
    volumes:
      - zap-reports:/zap/wrk
    networks:
      - internal-network
volumes:
  zap-reports:

networks:
  internal-network: